sudo: required

services:
  - docker

before_install:
- sudo apt-get update -qq
- sudo apt-get install -yq bash make

script:
- ls && pwd
- bash -c "pwd && for i in *; do test -d $i && sudo ./containnsm groupbuild $i; done"
